---
output: 
  pdf_document:
    citation_package: natbib
    keep_tex: true
    fig_caption: true
    latex_engine: pdflatex
    template: ./template.tex
title: "What Should _Financial_ Economists Do?"
author:
- name: Tyler J. Brough
  affiliation: Utah State University
abstract: "In this essay I argue for a stronger link between the Austrian School and financial economics."
keywords: "Austrian school, financial economics, catallactics"
date: "`r format(Sys.time(), '%B %d, %Y')`"
geometry: margin=1in
fontfamily: mathpazo
fontsize: 11pt
spacing: double
bibliography: ./master.bib
biblio-style: apsr
---


# Introduction

In his profound essay @Buchanan1964 asks: "What Should Economists Do?". In this essay, I ask a similar question but
direct my remarks to the field of finance. Here, I ask: "What Should ___Financial Economists___ Do?" My answer, 
following Buchanan, is that financial economists should focus on economic exchange rather than on the narrow topic of
economic optimization. I suggest that financial economists ought to be very comfortable with this paradigm. Indeed, the field of
market microstructure finance really is a ___catallactics___ of financial markets, though it does not go by that name.
Finance is a heavily empirical discipline, and as @Culp2004 has said, "it [is] quite hard to explain a lot of financial
and derivatives market activity without being a _little bit_ Austrian." My contention, is that financial economists
should actively embrace an Austrian foundation for the study of their discipline, and that if they do they will see the
questions they face with greater clarity.

Only rarely are works in the Austrian tradition cited in the modern finance literature. This despite the fact that much
of the modern theory of finance is founded on the ideas of informationally efficient prices following the foundational
ideas of @Hayek1945, such as the entire Efficient Markets Hypothesis literature. For example, neither of the papers by @Samuelson1965 and @Fama1970 cited @Hayek1945. Had they done so, I argue that greater clarity would have accompanied the following development of the modern finance literature. Thankfully, there are some rare exceptions such as @Grossman1989 and @Vives2010.  

Hayek has pointed out that arbitrage is the central concept in all of economics. See for example the discussion between
Buchanan and Hayek [@BuchananHayek] and the discussion by Israel Kirzner [@KirznerYT1]. While arbitrage is central to all of economics, nowhere in the broad economic literature has the concept been more developed than in finance. In the finance literature arbitrage has taken on a very specific definition requiring riskless profit (e.g. [@Varian1987] or [@DybvigRoss1989]). This has lead to a lack of coherence between theoretical finance and the vast literature on empirical finance. For example, the famed model of option pricing by @BlackScholes1973 requires that there be no arbitrage opportunities between the option and the dynamic hedge portfolio at every infinitesimal point in time. This extreme form of equilibrium theory is of course impossible, and taken literally is absurd. This has been implicitly understood by empirical researchers in finance. Still, young scholars in finance are often confused when moving from their theoretical asset pricing and empirical asset pricing courses. This is because theoretical finance is strongly grounded in neoclassical equilibrium theory, while empirical researchers have per force had to deal with real-world market dynamics evident in their data. I argue that a deeper understanding of Austrian market process theory would go a long way to harmonizing our understanding of theory and empirics. It will also help to focus our empirical lens by informing us on the nature of the questions that are amenable to econometric modeling.  

At the same time, many powerful statistical and econometric tools have been developed in the empirical finance
literature that ought to be informative to the rest of economics if indeed the arbitrage principle is central to
economics as Hayek thought. A powerful example of this is the work on cointegration and error correction models due to
@EngleGranger1987. This model has been given an explicit Austrian interpretation by @Mulligan2005. As @Koop2006 says:
"[I]t can be argued that cointegration is how macroeconomic equilibrium concepts should manifest themselves
empirically." As Mulligan points out without an understanding of market process theory it becomes very challenging to
understand the results of such a model. For a typical use of cointegration in finance see @Liu2005. Liu finds a
cointegrating relationship between hog, corn and soybean futures prices, suggesting a long-run (no-arbitrage)
equilibrium. At the same he finds that "ex-post trading simulations that utilize the cointegration results generate
significant profits, suggesting that market expectations may not fully incorporate the mean-reverting tendencies as
indicated by the cointegration relations, and that inefficiency exists in these three commodity futures markets." From
the perspective of neoclassical finance, this is indeed puzzling. But from an Austrian market process perspective this
is entirely expected. From this latter perspective markets are dynamically efficient and must per force allow for
arbitrage possibilities in the short-run. The empirical finance literature is chock-full of such findings. I argue that
other fields in economics can learn from the many empirical successes in empirical finance. Perhaps the most fruitful
application of this kind of empirical arbitrage-measurement thinking will be in the field of industrial organization. Indeed,
researchers such as @Spulber1999 have pointed out the connection between industrial organization and market
microstrucutre finance. By giving microstructure an explicit Austrian foundation many issues will be clarified.  

Despite the many empirical successes in finance there remains skepticism regarding the role of econometrics. See for
example, @Black1982, who is deeply skeptical of econometric methods as traditionally conceived. Here too the Austrian tradition informs of us how to understand these issues. @Hayek1994 wrote that our only knowledge of economic laws, was infact knowledge of a pattern, and that pattern prediction was the main methodological avenue of discovery. When viewed from this angle econometrics begins to look more like its modern cousins in the statistical sciences of statistical signal processing and machine learning. Financial market participants have discovered this as well. A inspection of job posting in quantitative finance rarely require skills in econometrics, while the latter are often cited as required. I argue that the best and most successful examples of financial econometrics can most profitable be understood from this angle. For example, the vast literature on cointegration in finance can be seen as prediction of pattern. Indeed, the central pattern in all of economics: arbitrage and the dynamic tendecy towards a single equilibrium price. In this light the examples of financial econometrics can be successfully applied in other fields in economics. 

In summary, in this essay I will seek to establish more concretely the linkage between modern financial economics and the Austrian school of thought. I will highlight the many ways in which finance has essentially re-discovered the foundational concepts of the informational role of prices due to @Hayek1945, and the central role of arbitrage in market process theory. 




